// system-apps/desktop-documentation-viewer/webClient/src/App.tsx
/*
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html
  
  SPDX-License-Identifier: EPL-2.0
  
  Copyright Contributors to the Zowe Project.
*/

import * as React from 'react';
import { MemoryRouter, Route } from 'react-router';
import Main from './Main';
import { withTranslation } from 'react-i18next';

class App extends React.Component<any, any> {
  private log: ZLUX.ComponentLogger;
  t: any;
  constructor(props){
    super(props);
    this.log = this.props.resources.logger;
    this.state = this.getDefaultState();
  };

  private getDefaultState() {
    return {
      docsList: "",
      pluginIdentifier: "",
      allPlugins: ZoweZLUX.pluginManager.loadPlugins("application", false).__zone_symbol__value,
      destination: ZoweZLUX.uriBroker.pluginRESTUri(this.props.resources.pluginDefinition.getBasePlugin(), 'plugindetail', "")
    };
  }

  updateOrInitState(stateUpdate: any): void {
    if (!this.state) {
      this.state = Object.assign(this.getDefaultState(), stateUpdate);
    }
    else {
      this.setState(stateUpdate);
    }
  }

  getPluginsFromServer() {
    let allPlugins = ZoweZLUX.pluginManager.loadPlugins("application", false);
    this.updateOrInitState({allPlugins: allPlugins.__zone_symbol__value})
  }

  getPluginDocsInfoFromServer(identifier: string) {
    let url = ZoweZLUX.uriBroker.pluginRESTUri(this.props.resources.pluginDefinition.getBasePlugin(), 'plugindetail', 'docs/'+`${identifier}`);
    fetch(url, {
      method: 'GET'
    })
      .then(res => {
        this.log.info(`Res=${res}`);
        res.json()
          .then((responseJson) => {
            if (responseJson) {
              this.setState({
                pluginIdentifier: identifier,
                docsList: responseJson.doc
              });
            }
          })
      });
  }

  postDocToServer(identifier: string, path: string) {
    let url = ZoweZLUX.uriBroker.pluginRESTUri(this.props.resources.pluginDefinition.getBasePlugin(), 'plugindetail', `${identifier}`);
    fetch(url, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        "identifier": identifier,
        "docLocation": path,
      }),
    })
      .then(res => {
        this.log.info(`Res=${res}`);
      })
  }

  public render(): JSX.Element {
    const { t } = this.props;
    this.t = t;
    return (
        <MemoryRouter
          initialEntries={[
            '/main'
          ]}>
        <div>
          <Route path="/main"
            render={(props) =>
              <Main {...props}
                allPlugins={this.state.allPlugins}
                docsList={this.state.docsList}
                pluginIdentifier={this.state.pluginIdentifier}
                postDocToServer={this.postDocToServer.bind(this)}
                getPluginDocsInfoFromServer={this.getPluginDocsInfoFromServer.bind(this)}
                getPluginsFromServer={this.getPluginsFromServer.bind(this)}
              />}
          />
        </div>
        </MemoryRouter>
    );
  }
}

export default withTranslation('translation')(App);

// system-apps/web-browser-app/webClient/src/app/app.component.ts


/*
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html

  SPDX-License-Identifier: EPL-2.0

  Copyright Contributors to the Zowe Project.
*/

import { Component, Inject } from '@angular/core';
import { Angular2InjectionTokens } from 'pluginlib/inject-resources';

import { LocaleService, TranslationService } from 'angular-l10n';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {

  constructor(
    public locale: LocaleService,
    public translation: TranslationService,
    @Inject(Angular2InjectionTokens.PLUGIN_DEFINITION) public pluginDefinition: ZLUX.ContainerPluginDefinition,
    @Inject(Angular2InjectionTokens.LOGGER) public log: ZLUX.ComponentLogger,
    @Inject(Angular2InjectionTokens.LAUNCH_METADATA) public launchMetadata: any,
  ) {
  }

  ngOnInit(): void {
    this.log.info(`web browser started`);
  }

}


/*
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html

  SPDX-License-Identifier: EPL-2.0

  Copyright Contributors to the Zowe Project.
*/


<!--
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html

  SPDX-License-Identifier: EPL-2.0

  Copyright Contributors to the Zowe Project.
-->

<app-browser>
</app-browser>

<!--
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html

  SPDX-License-Identifier: EPL-2.0

  Copyright Contributors to the Zowe Project.
-->
