// system-apps/app-prop-viewer/webClient/src/app/app.component.ts

/*
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html
  
  SPDX-License-Identifier: EPL-2.0
  
  Copyright Contributors to the Zowe Project.
*/
import { Component ,Inject} from '@angular/core';
import { Angular2InjectionTokens } from 'pluginlib/inject-resources';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

 

export class AppComponent { 
  appName:string;
  appVersion:string;
  appType:string;
  appId: string;
  copyright:string;
  installedApps:string[];
  iconImage:string;
  isPropertyWindow : boolean;
  isViewerWindow : boolean;

  constructor(
    @Inject(Angular2InjectionTokens.LAUNCH_METADATA) private launchMetadata: any
  ) {
    this.isPropertyWindow = false;
    this.isViewerWindow = true;
          
    if (this.launchMetadata != null && this.launchMetadata.data && this.launchMetadata.data.isPropertyWindow) {
      this.setInfoFromMessage(this.launchMetadata.data);
    } else if (this.launchMetadata != null && this.launchMetadata.data && this.launchMetadata.data.isViewerWindow){
      this.isViewerWindow=true;
    }
    
  }

  private setInfoFromMessage(message: any) {
    this.appName = message.appName;
    this.appVersion = message.appVersion;
    this.appId = message.appId;
    this.appType = message.appType;
    this.iconImage = message.image;
    this.isPropertyWindow = true;
    this.isViewerWindow = false;
    this.copyright=message.copyright;
  }

  zluxOnMessage(eventContext: any): Promise<any> {
    return new Promise((resolve,reject)=> {
      if (eventContext != null && eventContext.data && eventContext.data.isPropertyWindow) {
        resolve(this.setInfoFromMessage(eventContext.data));
      } else {
        reject('Event context missing or malformed');
      }
    });    
  }


  provideZLUXDispatcherCallbacks(): ZLUX.ApplicationCallbacks {
    return {
      onMessage: (eventContext: any): Promise<any> => {
        return this.zluxOnMessage(eventContext);
      }      
    }
  }
  
}

/*
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html
  
  SPDX-License-Identifier: EPL-2.0
  
  Copyright Contributors to the Zowe Project.
*/


<!-- 
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html
  
  SPDX-License-Identifier: EPL-2.0
  
  Copyright Contributors to the Zowe Project.
-->
@if(isViewerWindow){
<div class="viewer">
  TO VIEW ALL INSTALLED APPs
</div>
}

@if(isPropertyWindow){
<div class="window">
  
  <!-- Window body -->
  
  <div id="row" class="content">
    <div id="column1" class="icon" [style.background-image]="iconImage == null ? undefined : iconImage| cssUrl">
    </div>
      <div id="column2" >
      <p class="app-name">
       {{appName}}
      </p>
      <p class="app-value">
        <span class="constant">App Version</span>: {{appVersion}}
      </p> 
      <p class="app-value">
        <span class="constant">App ID</span>: {{appId}}
      </p> 
      <p class="app-value">
        <span class="constant">App Type</span>: {{appType}}
      </p>
       </div> 
  </div>
      <hr>
    <p class="copyright">
       {{copyright}}
      </p>
</div>
}
<!-- 
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html
  
  SPDX-License-Identifier: EPL-2.0
  
  Copyright Contributors to the Zowe Project.
-->

// system-apps/desktop-documentation-viewer/webClient/src/App.tsx
/*
  This program and the accompanying materials are
  made available under the terms of the Eclipse Public License v2.0 which accompanies
  this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html
  
  SPDX-License-Identifier: EPL-2.0
  
  Copyright Contributors to the Zowe Project.
*/

import * as React from 'react';
import { MemoryRouter, Route } from 'react-router';
import Main from './Main';
import { withTranslation } from 'react-i18next';

class App extends React.Component<any, any> {
  private log: ZLUX.ComponentLogger;
  t: any;
  constructor(props){
    super(props);
    this.log = this.props.resources.logger;
    let metadata = this.props.resources.launchMetadata;
    if (metadata != null && metadata.data != null && metadata.data.type != null) {
      this.handleLaunchOrMessageObject(metadata.data);
    } else {
      this.state = this.getDefaultState();
    }

  };

  private getDefaultState() {
    return {
      actionType: "Launch",
      appTarget: "PluginCreate",
      docsList: "",
      pluginIdentifier: "",
      allPlugins: ZoweZLUX.pluginManager.loadPlugins("application", false).__zone_symbol__value,
      destination: ZoweZLUX.uriBroker.pluginRESTUri(this.props.resources.pluginDefinition.getBasePlugin(), 'plugindetail', "")
    };
  }

  updateOrInitState(stateUpdate: any): void {
    if (!this.state) {
      this.state = Object.assign(this.getDefaultState(), stateUpdate);
    }
    else {
      this.setState(stateUpdate);
    }
  }

  handleLaunchOrMessageObject(data: any) {
    switch (data.type) {
    case 'setAppRequest':
      let actionType = data.actionType;
      let msg:string;
      if (actionType == 'Launch' || actionType == 'Message') {
        let mode = data.targetMode;
        if (mode == 'PluginCreate' || mode == 'PluginFindAnyOrCreate') {
          this.updateOrInitState({actionType: actionType,
                                  appTarget: mode,
                                  appId: data.targetAppId,
                                  parameters: data.requestText});
        } else {
          msg = `Invalid target mode given (${mode})`;
          this.log.warn(msg);
          this.updateOrInitState({status: msg});
        }
      } else {
        msg = `Invalid action type given (${actionType})`;
        this.log.warn(msg);
        this.updateOrInitState({status: msg});
      }
      break;
    default:
      this.log.warn(`Unknown command (${data.type}) given in launch metadata.`);
    }
  }

  zluxOnMessage(eventContext: any): Promise<any> {
    return new Promise((resolve,reject)=> {
      if (eventContext != null && eventContext.data != null && eventContext.data.type != null) {
        resolve(this.handleLaunchOrMessageObject(eventContext.data));
      } else {
        let msg = 'Event context missing or malformed';
        this.log.warn('onMessage '+msg);
        return reject(msg);
      }
    });
  }
  
  provideZLUXDispatcherCallbacks(): ZLUX.ApplicationCallbacks {
    return {
      onMessage: (eventContext: any): Promise<any> => {
        return this.zluxOnMessage(eventContext);
      }      
    }
  }  

  getPluginsFromServer() {
    let allPlugins = ZoweZLUX.pluginManager.loadPlugins("application", false);
    this.updateOrInitState({allPlugins: allPlugins.__zone_symbol__value})
  }

  getPluginDocsInfoFromServer(identifier: string) {
    let url = ZoweZLUX.uriBroker.pluginRESTUri(this.props.resources.pluginDefinition.getBasePlugin(), 'plugindetail', 'docs/'+`${identifier}`);
    fetch(url, {
      method: 'GET'
    })
      .then(res => {
        this.log.info(`Res=${res}`);
        res.json()
          .then((responseJson) => {
            if (responseJson) {
              this.setState({
                pluginIdentifier: identifier,
                docsList: responseJson.doc
              });
            }
          })
      });
  }

  getDoc(identifier: string, path: string) {
    let url = ZoweZLUX.uriBroker.pluginRESTUri(this.props.resources.pluginDefinition.getBasePlugin(), 'plugindetail', `${identifier}`);
    fetch(url, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        "identifier": identifier,
        "docLocation": path,
      }),
    })
      .then(res => {
        this.log.info(`Res=${res}`);
        console.log(res);
      })
  }

  public render(): JSX.Element {
    const { t } = this.props;
    this.t = t;
    return (
        <MemoryRouter
          initialEntries={[
            '/main'
          ]}>
        <div>
          <Route path="/main"
            render={(props) =>
              <Main {...props}
                allPlugins={this.state.allPlugins}
                docsList={this.state.docsList}
                pluginIdentifier={this.state.pluginIdentifier}
                getDoc={this.getDoc.bind(this)}
                getPluginDocsInfoFromServer={this.getPluginDocsInfoFromServer.bind(this)}
                getPluginsFromServer={this.getPluginsFromServer.bind(this)}
              />}
          />
        </div>
        </MemoryRouter>
    );
  }
}

export default withTranslation('translation')(App);
